name: Simple Workflow

on:
  push:
    branches: [ main ]

jobs:
  build:
    timeout-minutes: 120
    strategy:
      fail-fast: false
      matrix:
        java: [ 8 ]
        python-version: [ "3.9" ]
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        DB-name:
          [
            "FileSystem",
            "IoTDB12",
            "InfluxDB",
            "PostgreSQL",
            "Redis",
            "MongoDB",
            "Parquet",
          ]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Print DB name
        run: echo ${{ matrix.DB-name }}
